#!/usr/bin/env python2

#imports
from daemon import Daemon
import fapws._evwsgi as evwsgi
from fapws.contrib import django_handler, views
from fapws import base
import time
import sys, os

#setup environment
sys.setcheckinterval(100000) # since we don't use threads, internal checks are no more required
sys.path.append('/opt')
os.environ['DJANGO_SETTINGS_MODULE'] = 'settings'


class WebUIDaemon(Daemon):
	def run(self):
		start()
		while True:
			time.sleep(1)

def start():
	evwsgi.start("0.0.0.0", "80")
    
	evwsgi.set_base_module(base)
    
	def generic(environ, start_response):
		res=django_handler.handler(environ, start_response)
		return [res]
    
	static=views.Staticfile('/opt/webui/static/', maxage=2629000)
	evwsgi.wsgi_cb(("/static/",static))    
	evwsgi.wsgi_cb(('',generic))
    
	evwsgi.set_debug(0)
	evwsgi.run()

if __name__=="__main__":
	daemon = WebUIDaemon('/opt/webui/webui.pid')
	if len(sys.argv) == 2:
		if 'start' == sys.argv[1]:
			daemon.start()
		elif 'stop' == sys.argv[1]:
			daemon.stop()
		elif 'restart' == sys.argv[1]:
			daemon.restart()
		else:
			print "Unknown command"
			sys.exit(2)
		sys.exit(0)
	else:
		print "usage: %s start|stop|restart" % sys.argv[0]
		sys.exit(2)



